-- ============================================================================
--  SOCCER · HAXIOM EDGE · Tablas de Supabase (Fase 1)
-- ----------------------------------------------------------------------------
--  Todo es APPEND-ONLY por diseño (Signal Engine §2.1, POD §26): un snapshot,
--  una señal o un registro de auditoría nunca se sobreescriben; un cambio es
--  una fila nueva que apunta al snapshot que la produjo.
--
--  Seguridad: lectura pública (ver es libre), escritura solo dueños. Si existe
--  la función public.es_dueno() (rls-cerrar-escritura.sql) se usa; si no, se
--  permite a cualquier usuario autenticado, igual que el resto de la app.
--
--  Cómo correrlo: Supabase → SQL Editor → pega TODO → Run. Es idempotente.
-- ============================================================================

-- 1 · Snapshot inmutable de cada corrida (SE §2.1, POD §5) -------------------
create table if not exists public.futbol_snapshots (
  snapshot_id        text primary key,
  created_at         timestamptz not null default now(),
  slate_date         date not null,                 -- fecha del slate (zona America/New_York, supuesto S4)
  analysis_time      timestamptz not null,           -- hora exacta del análisis
  versions           jsonb not null,                 -- criterios, modelo, features, calibración, reglas, datos
  competitions       jsonb not null,                 -- competiciones evaluadas y su estado (con cuotas / sin cuotas / sin modelo)
  counts             jsonb not null,                 -- partidos, cuotas, candidatos, por tier
  input_hash         text not null,                  -- dq_snapshot_hash: hash del insumo crudo + versiones
  requests_used      integer,                        -- llamadas a API-Football en la corrida
  created_by         uuid default auth.uid()
);
create index if not exists futbol_snapshots_date on public.futbol_snapshots (slate_date, created_at desc);

-- 2 · Cotizaciones crudas por partido y snapshot (SE §2.1 "append every quote") -
create table if not exists public.futbol_cuotas (
  id            bigint generated by default as identity primary key,
  snapshot_id   text not null references public.futbol_snapshots(snapshot_id),
  fixture_id    bigint not null,
  quote_time    timestamptz,                         -- 'update' del proveedor (event time)
  ingest_time   timestamptz not null default now(),  -- cuándo lo recibió HAXIOM
  books         integer not null,
  quotes        jsonb not null                        -- [{book_id, book, bet_id, market, sel, line, dec, am}] originales + normalizadas
);
create index if not exists futbol_cuotas_fx on public.futbol_cuotas (fixture_id, ingest_time desc);

-- 3 · Registro de decisión por candidato evaluado (SE §1.2, §10; Master §8) ----
create table if not exists public.futbol_senales (
  id               bigint generated by default as identity primary key,
  snapshot_id      text not null references public.futbol_snapshots(snapshot_id),
  signal_id        text not null,                     -- único por snapshot
  candidate_key    text not null,                     -- fixture|market|sel|line (estable entre snapshots)
  created_at       timestamptz not null default now(),
  slate_date       date not null,
  competition_id   integer not null,
  competition      text not null,
  fixture_id       bigint not null,
  home             text not null,
  away             text not null,
  kickoff          timestamptz not null,
  canonical_market text not null,
  selection        text not null,
  line             numeric,
  book             text,
  odds_decimal     numeric,
  odds_american    integer,
  fair_decimal     numeric,
  p_model          numeric,                           -- probabilidad del ensamble (sin calibrar: calibration_version)
  p_novig          numeric,                           -- consenso no-vig (mediana de casas aprobadas)
  edge_pp          numeric,
  ev               numeric,
  ev_lcb           numeric,
  composite        numeric,
  percentile       numeric,
  data_quality     numeric,
  state            text not null,                     -- Elite Signal | Strong Signal | Lean Signal | Signal Detected | No Signal
  provisional_tier text,                              -- tier que alcanzaría con XI confirmado (SE §8 "qualify provisionally")
  reason_codes     text[] not null default '{}',
  min_decimal      numeric,                           -- precio mínimo aceptable para su tier
  expires_at       timestamptz,
  recheck_at       timestamptz,
  validation       text not null default 'PAPER',     -- PAPER hasta pasar la promoción SE §9.1
  record           jsonb not null                     -- objeto de decisión completo (SE §10)
);
create index if not exists futbol_senales_snap on public.futbol_senales (snapshot_id);
create index if not exists futbol_senales_key  on public.futbol_senales (candidate_key, created_at desc);
create index if not exists futbol_senales_date on public.futbol_senales (slate_date, state);

-- 4 · Prop of the Day: corrida y resultado (POD §25) ---------------------------
create table if not exists public.futbol_pod (
  id            bigint generated by default as identity primary key,
  snapshot_id   text not null references public.futbol_snapshots(snapshot_id),
  created_at    timestamptz not null default now(),
  slate_date    date not null,
  status        text not null,                        -- Candidate | Official | Pass | Invalidated | No Selection
  message       text not null,                        -- texto oficial de no-selección o descripción
  candidates    integer not null,
  eliminated    jsonb not null,                       -- conteo por reason code
  record        jsonb                                 -- registro POD §25 cuando hay líder/Official
);

-- 5 · Partidos jugados (resultados + estadísticas oficiales) — caché de modelo ---
create table if not exists public.futbol_partidos (
  fixture_id     bigint primary key,
  competition_id integer not null,
  season         integer not null,
  match_date     timestamptz not null,
  home_id        integer, away_id integer,
  home           text, away text,
  hg             integer, ag integer,
  ht_hg          integer, ht_ag integer,
  xg_h           numeric, xg_a numeric,               -- expected_goals agregado del proveedor (null = no disponible, NUNCA 0)
  stats          jsonb,                                -- estadísticas de equipo por partido (definition_version en el JSON)
  stats_at       timestamptz,
  inserted_at    timestamptz not null default now()
);
create index if not exists futbol_partidos_comp on public.futbol_partidos (competition_id, season, match_date);

-- 6 · Cierres: última cotización válida antes del inicio (SE §4.1 mkt_close_price)
create table if not exists public.futbol_cierres (
  id            bigint generated by default as identity primary key,
  fixture_id    bigint not null,
  captured_at   timestamptz not null default now(),
  minutes_to_ko numeric,
  snapshot_id   text references public.futbol_snapshots(snapshot_id),
  consensus     jsonb not null                        -- {market|sel|line: {p_novig, best_dec, books}}
);
create index if not exists futbol_cierres_fx on public.futbol_cierres (fixture_id, captured_at desc);

-- 7 · Resultados de señales publicadas (liquidación + CLV) ---------------------
create table if not exists public.futbol_resultados (
  id            bigint generated by default as identity primary key,
  signal_id     text not null,
  candidate_key text not null,
  snapshot_id   text not null,
  fixture_id    bigint not null,
  graded_at     timestamptz not null default now(),
  hg integer, ag integer,
  settlement    text not null,                        -- win | half_win | push | half_loss | loss | void
  return_units  numeric not null,
  close_p_novig numeric,
  clv_pp        numeric,                              -- close_p_novig − p_novig al publicar
  state_at_pub  text not null
);
create unique index if not exists futbol_resultados_sig on public.futbol_resultados (signal_id);

-- 8 · Auditoría: toda transición de estado con razón (SE §1.2 Audit, POD §26) ----
create table if not exists public.futbol_auditoria (
  id            bigint generated by default as identity primary key,
  at            timestamptz not null default now(),
  snapshot_id   text,
  candidate_key text,
  process       text not null,                        -- analysis | recheck | grade | close | pod
  prev_state    text,
  new_state     text,
  reason_codes  text[] default '{}',
  detail        jsonb
);
create index if not exists futbol_auditoria_key on public.futbol_auditoria (candidate_key, at desc);

-- 9 · RLS: lectura pública, escritura de dueños, sin UPDATE/DELETE (append-only) --
do $$
declare t text; hay_dueno boolean;
begin
  select exists (select 1 from pg_proc where proname = 'es_dueno') into hay_dueno;
  foreach t in array array['futbol_snapshots','futbol_cuotas','futbol_senales','futbol_pod',
                          'futbol_partidos','futbol_cierres','futbol_resultados','futbol_auditoria'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t||' read', t);
    execute format('create policy %I on public.%I for select using (true)', t||' read', t);
    execute format('drop policy if exists %I on public.%I', t||' owner insert', t);
    if hay_dueno then
      execute format('create policy %I on public.%I for insert to authenticated with check (public.es_dueno())', t||' owner insert', t);
    else
      execute format('create policy %I on public.%I for insert to authenticated with check (true)', t||' owner insert', t);
    end if;
    execute format('drop policy if exists %I on public.%I', t||' owner update', t);
    execute format('drop policy if exists %I on public.%I', t||' owner delete', t);
  end loop;
  -- futbol_partidos es caché: sí se actualiza (llegan estadísticas después del resultado)
  if hay_dueno then
    execute 'create policy "futbol_partidos owner update" on public.futbol_partidos for update to authenticated using (public.es_dueno()) with check (public.es_dueno())';
  else
    execute 'create policy "futbol_partidos owner update" on public.futbol_partidos for update to authenticated using (true) with check (true)';
  end if;
end $$;

-- Comprobación ----------------------------------------------------------------
select tablename, rowsecurity from pg_tables where schemaname='public' and tablename like 'futbol_%' order by 1;
