-- ============================================================================
--  MLB Picks Pro · Configuración de seguridad de Supabase (Row Level Security)
-- ----------------------------------------------------------------------------
--  Modelo de seguridad:
--    • LECTURA  (SELECT): pública  -> cualquiera puede ver picks e historial.
--    • ESCRITURA (INSERT/UPDATE/DELETE): solo usuarios AUTENTICADOS (el dueño).
--
--  La "anon key" del cliente es pública por diseño; la seguridad real la dan
--  estas políticas RLS. Sin esto, cualquier visitante podía borrar todo.
--
--  Cómo aplicarlo:
--    1. Supabase Dashboard -> SQL Editor -> New query.
--    2. Pega TODO este archivo y ejecútalo (Run).
--    3. Authentication -> Providers -> Email: déjalo habilitado.
--    4. Authentication -> Users -> Add user: crea TU usuario (email+password).
--       (Opcional: desactiva "Allow new users to sign up" para que nadie más
--        pueda registrarse.)
-- ============================================================================

-- Asegura que las tablas existen (no-op si ya están creadas) ------------------
create table if not exists public.predictions (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now(),
  game_date       date,
  away            text,
  home            text,
  venue           text,
  fav             text,
  fav_prob        numeric,
  confidence      text,
  predicted_total numeric,
  home_wp         numeric,
  away_wp         numeric,
  home_ml         text,
  away_ml         text,
  top_pick_cat    text,
  top_pick_main   text,
  top_pick_prob   numeric,
  top_pick_edge   numeric,
  all_picks_json  text,
  result          text,         -- 'win' | 'loss' | 'push' | null
  top_pick_price  numeric,      -- cuota americana a la que se "apostó"
  top_pick_fair   numeric,      -- prob. justa del mercado (sin vig) al apostar
  close_fair      numeric,      -- prob. justa del mercado al CIERRE (capturada luego)
  clv             numeric       -- Closing Line Value = close_fair - top_pick_fair
);

-- Por si la tabla ya existía: agrega las columnas nuevas (idempotente) ---------
alter table public.predictions add column if not exists top_pick_price numeric;
alter table public.predictions add column if not exists top_pick_fair  numeric;
alter table public.predictions add column if not exists close_fair      numeric;
alter table public.predictions add column if not exists clv             numeric;
alter table public.predictions add column if not exists features_json  text;     -- features del modelo (para reentrenar)
alter table public.predictions add column if not exists home_won       integer;  -- 1 si ganó el local, 0 si no

create table if not exists public.model_weights (
  id           bigint primary key,
  weights_json text,
  train_iter   bigint
);

-- Caché del análisis COMPLETO (para restaurar desde cualquier dispositivo) -----
create table if not exists public.analysis_cache (
  game_date  text primary key,    -- fecha analizada (YYYY-MM-DD)
  payload    text,                -- JSON con games/batters/parlays/bprops
  updated_at timestamptz default now()
);

-- SEÑALES · historial del tablero de convicción -------------------------------
--  Una fila por juego analizado con su Edge Read (equipo señalado, tier, convicción
--  efectiva, data quality, mejor aplicación). Después se califica desde el marcador
--  final: ML del equipo señalado y F5. La clave es (game_date, game_pk), así que los
--  doubleheaders se guardan y califican por separado.
create table if not exists public.signals (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now(),
  game_date       date,
  game_pk         bigint,
  away            text,
  home            text,
  venue           text,
  edge_team       text,      -- equipo con la ventaja según el tablero
  tier            text,      -- 'NO EDGE' | 'LEAN' | 'STRONG' | 'ELITE'
  conv_eff        numeric,   -- convicción ya atenuada por Data Quality
  net_abs         numeric,   -- convicción bruta (sin atenuar)
  net             numeric,   -- signo: + = ventaja del LOCAL
  dq              integer,   -- Data Quality 0-100
  park_pts        numeric,   -- lectura de park/weather (puntos de total)
  best_bet        text,      -- mejor aplicación sugerida (F5 / Team Total / ML / RL)
  edge_wp         numeric,   -- prob. del MODELO para el equipo señalado (¿coinciden?)
  predicted_total numeric,
  lines_json      text,      -- las 10 categorías del Edge Read
  flags_json      text,      -- red flags, conflictos y notas de DQ
  home_score      integer,
  away_score      integer,
  f5_home         integer,
  f5_away         integer,
  result          text,      -- ML del equipo señalado: 'win' | 'loss' | 'push' | null
  f5_result       text       -- F5 del equipo señalado: 'win' | 'loss' | 'push' | null
);
-- Mercado que recomendó el tablero, normalizado para poder calificarlo. Es lo ÚNICO
-- que se califica: si el tablero dijo F5, se mide F5 y no el ML. 'Team Total Over' es
-- el único que necesita guardar su línea, porque el texto del tablero no la lleva.
alter table public.signals add column if not exists best_mkt  text;      -- 'ML' | 'F5' | 'TT' | 'RL'
alter table public.signals add column if not exists best_line numeric;   -- línea del team total (solo TT)

create unique index if not exists signals_game on public.signals (game_date, game_pk);
create index if not exists signals_tier on public.signals (tier);

alter table public.signals enable row level security;
drop policy if exists "signals public read" on public.signals;
drop policy if exists "signals auth write"  on public.signals;
drop policy if exists "signals auth update" on public.signals;
drop policy if exists "signals auth delete" on public.signals;
create policy "signals public read" on public.signals for select using (true);
create policy "signals auth write"  on public.signals for insert to authenticated with check (true);
create policy "signals auth update" on public.signals for update to authenticated using (true) with check (true);
create policy "signals auth delete" on public.signals for delete to authenticated using (true);

-- Historial de props (pitchers Ks y bateadores) ------------------------------
create table if not exists public.prop_picks (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  game_date   text, game_pk bigint,
  kind        text,       -- 'pitcher' | 'batter'
  player_id   bigint, player_name text, team text,
  market      text,       -- 'Ks' | 'Hit' | 'TB' | 'H+R+RBI' | 'BB' | 'HR'
  target      numeric, side text, prob numeric, proj numeric,
  actual      numeric, result text   -- 'win' | 'loss' | null
);

-- 1) Activar RLS --------------------------------------------------------------
alter table public.predictions     enable row level security;
alter table public.model_weights   enable row level security;
alter table public.analysis_cache  enable row level security;
alter table public.prop_picks      enable row level security;

-- 2) Borrar políticas previas (idempotente) -----------------------------------
drop policy if exists "props public read"          on public.prop_picks;
drop policy if exists "props auth write"           on public.prop_picks;
drop policy if exists "props auth update"          on public.prop_picks;
drop policy if exists "props auth delete"          on public.prop_picks;
drop policy if exists "cache public read"          on public.analysis_cache;
drop policy if exists "cache auth write"           on public.analysis_cache;
drop policy if exists "cache auth update"          on public.analysis_cache;
drop policy if exists "predictions public read"    on public.predictions;
drop policy if exists "predictions auth write"     on public.predictions;
drop policy if exists "predictions auth update"    on public.predictions;
drop policy if exists "predictions auth delete"    on public.predictions;
drop policy if exists "weights public read"        on public.model_weights;
drop policy if exists "weights auth write"         on public.model_weights;
drop policy if exists "weights auth update"        on public.model_weights;

-- 3) predictions: lectura pública, escritura solo autenticado -----------------
create policy "predictions public read"
  on public.predictions for select
  using (true);

create policy "predictions auth write"
  on public.predictions for insert
  to authenticated
  with check (true);

create policy "predictions auth update"
  on public.predictions for update
  to authenticated
  using (true) with check (true);

create policy "predictions auth delete"
  on public.predictions for delete
  to authenticated
  using (true);

-- 4) model_weights: lectura pública, escritura solo autenticado ---------------
create policy "weights public read"
  on public.model_weights for select
  using (true);

create policy "weights auth write"
  on public.model_weights for insert
  to authenticated
  with check (true);

create policy "weights auth update"
  on public.model_weights for update
  to authenticated
  using (true) with check (true);

-- 5) analysis_cache: lectura pública, escritura solo autenticado ---------------
create policy "cache public read"
  on public.analysis_cache for select
  using (true);

create policy "cache auth write"
  on public.analysis_cache for insert
  to authenticated
  with check (true);

create policy "cache auth update"
  on public.analysis_cache for update
  to authenticated
  using (true) with check (true);

-- 6) prop_picks: lectura pública, escritura solo autenticado -------------------
create policy "props public read"  on public.prop_picks for select using (true);
create policy "props auth write"   on public.prop_picks for insert to authenticated with check (true);
create policy "props auth update"  on public.prop_picks for update to authenticated using (true) with check (true);
create policy "props auth delete"  on public.prop_picks for delete to authenticated using (true);

-- Resultados de fútbol cosechados de odds-api.io (alimentan el modelo Dixon-Coles) ----
--  Cada análisis guarda aquí los marcadores finales ('settled'); al juntar >=30
--  partidos por liga de la temporada actual, se encienden las fuerzas del modelo.
create table if not exists public.soccer_results (
  event_id   text primary key,       -- id del evento en odds-api.io (dedup por upsert)
  league     text,                    -- key interna (soccer_epl, soccer_mexico_ligamx, …)
  season     integer,                 -- año de inicio de la temporada (jul→jun)
  match_date timestamptz,
  home       text,
  away       text,
  home_goals integer,
  away_goals integer,
  created_at timestamptz default now()
);
create index if not exists soccer_results_league_season on public.soccer_results (league, season);

alter table public.soccer_results enable row level security;
drop policy if exists "soccer_results public read" on public.soccer_results;
drop policy if exists "soccer_results auth write"   on public.soccer_results;
drop policy if exists "soccer_results auth update"  on public.soccer_results;
create policy "soccer_results public read" on public.soccer_results for select using (true);
create policy "soccer_results auth write"  on public.soccer_results for insert to authenticated with check (true);
create policy "soccer_results auth update" on public.soccer_results for update to authenticated using (true) with check (true);

-- Listo. Con esto:
--   • Visitantes anónimos: solo pueden LEER (ver picks e historial).
--   • Tú (autenticado): puedes generar, guardar, calificar y borrar.

-- ============================================================================
--  app_config : la API key de The Odds API, atada a TU usuario
-- ----------------------------------------------------------------------------
--  Por que aqui y no en el codigo: este repo es publico y GitHub Pages sirve el
--  index.html tal cual, asi que una key escrita en el codigo queda visible para
--  cualquiera (y hay bots que escanean GitHub buscando justo eso). Guardandola
--  aqui queda fija en todos tus dispositivos sin publicarse nunca.
--
--  OJO: esta tabla NO tiene lectura publica, a diferencia de las demas. Cada
--  usuario solo ve y escribe SU propia fila (auth.uid() = user_id). Un visitante
--  anonimo no puede leerla.
-- ============================================================================
create table if not exists public.app_config (
  user_id       uuid primary key references auth.users(id) on delete cascade,
  odds_api_key  text,
  updated_at    timestamptz default now()
);

alter table public.app_config enable row level security;

drop policy if exists "app_config owner read"   on public.app_config;
drop policy if exists "app_config owner insert" on public.app_config;
drop policy if exists "app_config owner update" on public.app_config;
drop policy if exists "app_config owner delete" on public.app_config;

create policy "app_config owner read"   on public.app_config
  for select to authenticated using (auth.uid() = user_id);
create policy "app_config owner insert" on public.app_config
  for insert to authenticated with check (auth.uid() = user_id);
create policy "app_config owner update" on public.app_config
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "app_config owner delete" on public.app_config
  for delete to authenticated using (auth.uid() = user_id);
